# Generated by Django 3.1.7 on 2021-03-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techmelaApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('1', 'Robotics'), ('2', 'Assitive Technology'), ('3', 'Software Projects')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='mainDescription',
            field=models.TextField(),
        ),
    ]
